name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
            ~/.cargo/registry
            ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
            ${{ runner.os }}-cargo-
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: Build
      run: cargo build --verbose
    - name: Cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --workspace --all-targets --all

  coding-style:
    name: Coding Style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
            ~/.cargo/registry
            ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
            ${{ runner.os }}-cargo-
    - name: Install clippy
      run: rustup component add clippy
    - name: Run linter (clippy)
      run: cargo clippy -- -D warnings
