name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --all-features

      - name: Save built extension into artifcat
        uses: actions/upload-artifact@v3
        with:
          name: ext-redlock-php
          path: target/release/libext_redlock_php.so

  coding-style:
    name: Coding Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install clippy
        run: rustup component add clippy

      - name: Run linter (clippy)
        run: cargo clippy -- -D warnings
